CREATE TABLE orders
(
    id             UUID PRIMARY KEY,
    client_id      UUID           NOT NULL,
    amount         NUMERIC(19, 2) NOT NULL CHECK (amount > 0),
    status         VARCHAR(16)    NOT NULL,
    business_day   DATE           NOT NULL,
    limit_released BOOLEAN        NOT NULL DEFAULT FALSE,
    status_reason  VARCHAR(512),
    created_at     TIMESTAMPTZ    NOT NULL,
    updated_at     TIMESTAMPTZ    NOT NULL
);

CREATE INDEX idx_orders_client_day ON orders (client_id, business_day);
CREATE INDEX idx_orders_stuck ON orders (updated_at) WHERE status = 'PROCESSING';

CREATE TABLE order_status_history
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    UUID        NOT NULL REFERENCES orders (id),
    from_status VARCHAR(16),
    to_status   VARCHAR(16) NOT NULL,
    reason      VARCHAR(512),
    created_at  TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_history_order ON order_status_history (order_id, id);

CREATE TABLE client_daily_limit
(
    client_id    UUID           NOT NULL,
    business_day DATE           NOT NULL,
    daily_limit  NUMERIC(19, 2) NOT NULL CHECK (daily_limit > 0),
    reserved     NUMERIC(19, 2) NOT NULL DEFAULT 0 CHECK (reserved >= 0),
    PRIMARY KEY (client_id, business_day),
    CONSTRAINT reserved_within_limit CHECK (reserved <= daily_limit)
);

CREATE TABLE idempotency_record
(
    idempotency_key     UUID PRIMARY KEY,
    request_fingerprint VARCHAR(128) NOT NULL,
    order_id            UUID         NOT NULL REFERENCES orders (id),
    created_at          TIMESTAMPTZ  NOT NULL
);

CREATE TABLE outbox_message
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_id UUID         NOT NULL,
    event_type   VARCHAR(64)  NOT NULL,
    routing_key  VARCHAR(128) NOT NULL,
    payload      TEXT         NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL,
    published_at TIMESTAMPTZ
);

CREATE INDEX idx_outbox_unpublished ON outbox_message (id) WHERE published_at IS NULL;
